BlackJack.MVC/Controllers/GameController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using BlackJack.BusinessLogic.Enums;
using BlackJack.BusinessLogic.Exceptions;
using BlackJack.BusinessLogic.Services.Interfaces;
using BlackJack.ViewModels.EnumViews;
using BlackJack.ViewModels.SharedViews;

namespace BlackJack.MVC.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService _gameService;
        public GameController(IGameService gameService)
        {
            _gameService = gameService;
        }

        public async Task<ActionResult> GetStart()
        {
            var allHumanPlayer = await _gameService.GetStart();
            return View("Start",allHumanPlayer);
        }


        public async Task<ActionResult> PlayCurrentGame(int id, GetCardEnum getCardEnum)
        {
            ModelState.Clear();
            try
            {
                var startGame = await _gameService.PlayCurrentGame(id, getCardEnum);
                if (getCardEnum == GetCardEnum.Start && !(startGame.CheckEndGame == GameEndEnumView.EndGame))
                {
                    return View("CurrentGame",startGame);
                }
                if (startGame.CheckEndGame == GameEndEnumView.EndGame && getCardEnum == GetCardEnum.Start)
                {
                    return RedirectToAction("GetEndGame", "Game", new { id });
                }
                if (getCardEnum == GetCardEnum.Take && (startGame.CheckEndGame == GameEndEnumView.ContinueGame))
                {
                    return View("_CreateNextRoundGameView", startGame);
                }
                return Json(new
                {
                    url = Url.Action("GetEndGame", "Game", new { id }),
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                ErrorView errorGameView = new ErrorView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }

        }

        [HttpPost]
        public async Task<ActionResult> CreateGame(string currentPlayer, int botsCount)
        {
            try
            {
                var startGame = await _gameService.CreateGame(currentPlayer, botsCount);
                return RedirectToAction("PlayCurrentGame", "Game", new { id = startGame, GetCardEnum = GetCardEnum.Start });
            }
            catch (AppValidationException e)
            {
                ErrorView errorGameView = new ErrorView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
            catch (Exception e)
            {
                ErrorView errorGameView = new ErrorView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }

        public async Task<ActionResult> GetEndGame(int id)
        {
            try
            {
                var endGame = await _gameService.GetEndGame(id);
                return View("EndGame",endGame);
            }
            catch (Exception e)
            {
                ErrorView errorGameView = new ErrorView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }
    }
}

BlackJack.MVC/Controllers/HistoryController.cs
using BlackJack.BusinessLogic.Services.Interfaces;
using BlackJack.ViewModels.SharedViews;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BlackJack.MVC.Controllers
{
    public class HistoryController : Controller
    {
        private readonly IHistoryService _historyService;
        public HistoryController(IHistoryService historyService)
        {
            _historyService = historyService;
        }

        public async Task<ActionResult> GetAllGames()
        {
            try
            {
                var allGames = await _historyService.GetAllGames();
                return View("AllGames",allGames);
            }
            catch (Exception e)
            {
                ErrorView errorGameView = new ErrorView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }

        public async Task<ActionResult> GetGameDetails(int id)
        {
            try
            {
                var gameDetails = await _historyService.GetGameDetails(id);
                return View("GameDetails", gameDetails);
            }
            catch (Exception e)
            {
                ErrorView errorGameView = new ErrorView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }
    }
}

BlackJack.MVC/Views/Game/CurrentGame.cshtml
@using BlackJack.ViewModels.GameViews
@using BlackJack.BusinessLogic.Enums
@model PlayCurrentGameGameView
@{
    ViewBag.Title = "Games";
}
<div>
    <center><h4>Game # @Model.GameId.ToString()</h4></center>
    <center>
        <div id="results">
            @{
                Html.RenderPartial("_CreateNextRoundGameView");
            }
        </div>
        @using (Ajax.BeginForm("PlayCurrentGame", "Game", new AjaxOptions { UpdateTargetId = "results", OnSuccess = "onSuccess", HttpMethod = "Post" }))
        {
            @Html.Hidden("id", Model.GameId);
            GetCardEnum getCardEnum = GetCardEnum.Take;
            @Html.Hidden("getCardEnum", getCardEnum)
            <div id="button_block">
                <button id="button_take" type="submit">Take more</button>
            </div>
        }
        <br />
        @using (Html.BeginForm("GetEndGame", "Game", FormMethod.Post))
        {
            @Html.Hidden("id", Model.GameId)
            <div id="button_block">
                <button id="button_enough" type="submit">Enough</button>
            </div>
        }
        <br />
        <br />
    </center>
</div>
@Scripts.Render("~/bundles/Game/CurrentGame")
@Scripts.Render("~/scripts/jquery-3.3.1.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")

BlackJack.MVC/Views/Game/EndGame.cshtml
@using BlackJack.ViewModels.GameViews
@model GetEndGameGameView
@{
    ViewBag.Title = "EndGame";
}
<center><h2>End of Game</h2></center>
<center><h2>Result</h2></center>
<center>
    <table class="table1">
        <tr><th>Name </th><th>Role </th><th>Cards </th><th>Total points </th><th>Status </th></tr>
        @foreach (var players in Model.Players)
        {
            <tr>
                <td>@players.Name</td>
                <td>@players.Role.ToString()</td>
                <td>
                    @for (int i = 0; i < players.PlayerCards.Count; i++)
                    {
                        @players.PlayerCards[i].Name.ToString()<text></text> @players.PlayerCards[i].Suit.ToString()<text></text> @players.PlayerCards[i].Points
                        <br />
                    }
                </td>
                <td>
                    @players.CardSum.ToString()
                </td>
                <td>
                    @players.PlayerStatus.ToString()
                </td>
            </tr>
        }
        <tr>
            <td>@Model.DealerPlayer.Name</td>
            <td>@Model.DealerPlayer.Role.ToString()</td>
            <td>
                @for (int i = 0; i < @Model.DealerPlayer.PlayerCards.Count; i++)
                {
                    @Model.DealerPlayer.PlayerCards[i].Name.ToString()<text></text> @Model.DealerPlayer.PlayerCards[i].Suit.ToString()<text></text> @Model.DealerPlayer.PlayerCards[i].Points
                    <br />
                }
            </td>
            <td>
                @Model.DealerPlayer.CardSum.ToString()
            </td>
            <td>
                -
            </td>
        </tr>
    </table>
    <br />
    @using (Html.BeginForm("GetStart", "Game", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_start_new_game" type="submit">Start new game</button>
        </div>
    }
    <br />
    @using (Html.BeginForm("GetAllGames", "History", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_view_history" type="submit">View history</button>
        </div>
    }
</center>
@Scripts.Render("~/bundles/Game/EndGame")

BlackJack.MVC/Views/Game/Start.cshtml
@using BlackJack.ViewModels.GameViews
@model GetStartGameView
@{
    List<string> HumanPLayers = new List<string>();
    foreach(var player in Model.HumanPlayers)
    {
        HumanPLayers.Add(player.Name);
    }
    ViewBag.Title = "BlackJack";
}
<center><h1>Welcome to the game</h1></center>
<center>
    <div class="startGame">
        @using (Html.BeginForm("CreateGame", "Game", FormMethod.Post))
        {
            <h4>Enter your name or select player</h4>
            <input id="humanPlayers" name="currentPlayer" />
            <h4>Choose count bot-player</h4>
            <input id="botsCount" name="botsCount" />
            <h4>and start game</h4>
            <button id="button_start" type="submit">Start</button>
        }
    </div>
</center>
<script>
    var array = JSON.parse('@Newtonsoft.Json.JsonConvert.SerializeObject(HumanPLayers)'.replace(/&quot;/g, "\""));   
</script>
@Scripts.Render("~/bundles/Game/Start")

BlackJack.MVC/Views/Game/_CreateNextRoundGameView.cshtml
@using BlackJack.ViewModels.GameViews
@model PlayCurrentGameGameView
<table class="table1">
    <tr><th>Name </th><th>Role </th><th>Cards </th><th>Total points </th><th>Status </th></tr>
    @foreach (var players in Model.Players)
    {
        <tr>
            <td>@players.Name</td>
            <td>@players.Role.ToString()</td>
            <td>
                @for (int i = 0; i < players.PlayerCards.Count; i++)
                {
                    @players.PlayerCards[i].Name.ToString()<text></text> @players.PlayerCards[i].Suit.ToString()<text></text> @players.PlayerCards[i].Points
                    <br />
                }
            </td>
            <td>
                @players.CardSum.ToString()
            </td>
            <td>
                @players.PlayerStatus.ToString()
            </td>
        </tr>
    }
    <tr>
        <td>@Model.DealerPlayer.Name</td>
        <td>@Model.DealerPlayer.Role.ToString()</td>
        <td>
            @for (int i = 0; i < @Model.DealerPlayer.PlayerCards.Count; i++)
            {
                @Model.DealerPlayer.PlayerCards[i].Name.ToString()<text></text> @Model.DealerPlayer.PlayerCards[i].Suit.ToString()<text></text> @Model.DealerPlayer.PlayerCards[i].Points
                <br />
            }
        </td>
        <td>
            @Model.DealerPlayer.CardSum.ToString()
        </td>
        <td>
            -
        </td>
    </tr>
</table>
<br>

BlackJack.MVC/Views/History/AllGames.cshtml
@using BlackJack.ViewModels.HistoryViews
@model GetAllGamesHistoryView
@{
    ViewBag.Title = "AllGames";
}
<center>
    <h2>All Games</h2>
</center>
<center>
    <div id="allGames" style="width:500px"></div>
</center>
<br />
<br />
<center>
    @using (Html.BeginForm("GetStart", "Game", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_start_new_game" type="submit">Start new game</button>
        </div>
    }
</center>
<script>
    var data = JSON.parse('@Newtonsoft.Json.JsonConvert.SerializeObject(Model.Games)'.replace(/&quot;/g, "\""));
</script>
@Scripts.Render("~/bundles/jquery.min")
@Scripts.Render("~/bundles/kendo.all.min")
@Scripts.Render("~/bundles/History/AllGames")

BlackJack.MVC/Views/History/GameDetails.cshtml
@using BlackJack.ViewModels.HistoryViews
@model GetGameDetailsHistoryView
@{
    ViewBag.Title = "GameDetails";
}
<center>
    <h2>Game details number @Model.GameId </h2>
</center>
<center>
    <table class="table1">
        <tr><th>Name </th><th>Role </th><th>Cards </th><th>Total points </th><th>Status </th></tr>
        @foreach (var players in Model.Players)
        {
            <tr>
                <td>@players.Name</td>
                <td>@players.Role.ToString()</td>
                <td>
                    @for (int i = 0; i < players.PlayerCards.Count; i++)
                    {
                        @players.PlayerCards[i].Name.ToString()<text></text> @players.PlayerCards[i].Suit.ToString()<text></text> @players.PlayerCards[i].Points
                        <br />
                    }
                </td>
                <td>
                    @players.CardSum.ToString()
                </td>
                <td>
                    @players.PlayerStatus.ToString()
                </td>
            </tr>
        }
        <tr>
            <td>@Model.DealerPlayer.Name</td>
            <td>@Model.DealerPlayer.Role.ToString()</td>
            <td>
                @for (int i = 0; i < @Model.DealerPlayer.PlayerCards.Count; i++)
                {
                    @Model.DealerPlayer.PlayerCards[i].Name.ToString()<text></text> @Model.DealerPlayer.PlayerCards[i].Suit.ToString()<text></text> @Model.DealerPlayer.PlayerCards[i].Points
                    <br />
                }
            </td>
            <td>
                @Model.DealerPlayer.CardSum.ToString()
            </td>
            <td>
                -
            </td>
        </tr>
    </table>
    <br />
    @using (Html.BeginForm("GetAllGames", "History", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_view_history" type="submit">Return to history</button>
        </div>
    }
</center>
@Scripts.Render("~/bundles/History/GameDetails")

BlackJack.MVC/Views/Shared/_Error.cshtml
@using BlackJack.ViewModels.SharedViews
@model ErrorView

<center>
    <h2>@Model.Error.ToString()</h2>
    <br />
    <img src="https://tincan.co.uk/sites/default/files/styles/banner_image_tincan/public/images/Blog-404-01.png?itok=G8jyKL7k" width="700" height="400"/>
    @using (Html.BeginForm("GetStart", "Game", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_start_new_game" type="submit">Try again</button>
        </div>
    }
</center>
@Scripts.Render("~/bundles/Game/Error")

BlackJack.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.620/styles/kendo.common-material.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.620/styles/kendo.material.mobile.min.css" />
    <script src="https://kendo.cdn.telerik.com/2018.2.620/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.2.620/js/kendo.all.min.js"></script>
    @Styles.Render("~/Content/style")
    @Styles.Render("~/Content/kendo.material.min")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Start Game", "GetStart", "Game", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("History Game", "GetAllGames", "History", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>